name: "Continuous delivery"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "Guildedgo dev release"
          automatic_release_tag: "latest"'
          prerelease: true
